### ISSUE TITLE
[Issue] Spotify stops working while installed

### ISSUE THREAD

**Issue by knapdragon** [An0n-00/SpotifyAB#3]
Spotify does not properly load and gets stuck in a restart loop after SpotifyAB installation.

![Spotify_zMP1IZieJy](https://github.com/user-attachments/assets/bb72e441-f723-4067-8f75-85a0102f38c3)

**Comment by An0n-00** [comment]
Hm interesting... were you logged in before installing spotifyAB?

**Comment by knapdragon** [comment]
Yes. For the record, I also have the hosts file populated with the domains from the old ad-block method, which no longer works anymore. I tried removing those domains but this didn't change anything.

**Comment by An0n-00** [comment]
hmm... I cannot recreate this issue.. I just reinstalled spotify completly and it still works...

Try "fixing" the currently installed spotify version by downloading the installer (official spotify) again and running it:

`https://download.scdn.co/SpotifySetup.exe`

SpotifyAB might still think that it is installed (which it isnt anymore if you run the installer). To fix that you will have to edit a key in the registry.... but try this... (and yes i would remove all the hosts from the old repo from the host file)

**Comment by An0n-00** [comment]
(btw, i am planning to fix that in the next update for the client 😄 )

**Comment by knapdragon** [comment]
This fixed the issue, I think my Spotify install must have simply been out of date. Thank you for the application, also.

**Comment by An0n-00** [comment]
@knapdragon you can now download the [new client](https://github.com/An0n-00/SpotifyAB/releases/latest/download/SpotifyAB-Installer.exe). It automatically checks if spotify updated itself and installs spotifyAB again, fixing issues like the one you've faced. 


If you encounter any [issues](https://github.com/An0n-00/SpotifyAB/issues) or have suggestions, feel free to open an [issue](https://github.com/An0n-00/SpotifyAB/issues) on GitHub.
